### ISSUE TITLE
button doesnt show up in RSGL ?????

### ISSUE THREAD

**Issue by 256colormode** [ColleagueRiley/RSGL#4]
hi, so when i compile RSGL's button.c example, nothing shows up.
note: i compiled this on mac os

**Comment by ColleagueRiley** [comment]
Hello, thank you for filing this error. Could you provide more information? Specifically, what version of MacOS are you using, is the window showing up or is it just an issue with rendering and do the other examples render properly for you?

**Comment by 256colormode** [comment]
im using catalina

**Comment by 256colormode** [comment]
so i have fixed the button.c code but it only shows the window, it doesnt show the buttons

**Comment by ColleagueRiley** [comment]
Cool, I will look into the issue as soon as I can. Right now I think the issue could be one of four possible problems. 

1) RGFW is not properly loading an OpenGL context properly.
2) MacOS doesn't like something RGL is doing.
3) MacOS doesn't like something RSGL is doing.
4) Something with your hardware or drivers end isn't working properly with RSGL (or it's dependencies). This could an issue with the ARM processor if your device is using an ARM processor. 

I can narrow it down if other forms of rendering are working with MacOS.

**Comment by ColleagueRiley** [comment]
Update:

I was able to fix the macOS rendering issue for legacy OpenGL. However there is a shader error that seems to only exist for MacOS.

**Comment by ColleagueRiley** [comment]
I've not yet tested it but the latest push I did might have solved this issue

**Comment by ColleagueRiley** [comment]
This issue should be solved now. I tested it with High Sierra.

**Comment by 256colormode** [comment]
> This issue should be solved now. I tested it with High Sierra.

TYSMMMMMMMM

**Comment by ColleagueRiley** [comment]
I also noticed that the mouse move event data is incorrect. Though this is a separate issue with RGFW or Silicon. I will be looking into it later today.

**Comment by ColleagueRiley** [comment]
> I also noticed that the mouse move event data is incorrect. Though this is a separate issue with RGFW or Silicon. I will be looking into it later today.

This has been fixed in the latest update.

**Comment by 256colormode** [comment]
im gettng "Segmentation fault: 11" when opening button.c and sometimes it works but the button still doesnt show up, well guess im moving to rgfw

**Comment by ColleagueRiley** [comment]
That's weird, I didn't get that issue while I was testing. Could you provide some more information please?

**Comment by 256colormode** [comment]
so can u send me the screenshot of when u were running button.c on mac os

**Comment by ColleagueRiley** [comment]
Of course, I planned to later. I am still busy currently so I will send the screenshots later.

**Comment by 256colormode** [comment]
k

**Comment by ColleagueRiley** [comment]
![image](https://github.com/ColleagueRiley/RSGL/assets/50218871/c1e27af7-82f0-4d77-8fda-cdb08e1764a0)

I didn't get a seg fault either.

**Comment by ColleagueRiley** [comment]
![image](https://github.com/ColleagueRiley/RSGL/assets/50218871/50d0b67f-a01b-4e8c-b4fa-41cf171db12e)

(this is using MacOS macOS High Sierra) 

It didn't give me any segmentation faults.
There was lag caused by RGFW, this has been fixed in the latest commit.

**Comment by 256colormode** [comment]
so does rsgl use cocoa

**Comment by ColleagueRiley** [comment]
Yes, RSGL uses RGFW which uses Cocoa via Silicon.h

**Comment by 256colormode** [comment]
but does button.c use cocoa

**Comment by ColleagueRiley** [comment]
Yes, again RSGL uses RGFW which uses Cocoa via Silicon.h. 

In case you're confused, Cocoa is not used here for rendering or creation of GUIs. Cocoa is only used here for the management of windows, window events (including mouse events), etc.

Also, considering this thread is becoming longer and less focused, feel free to add me on Discord (if you have it) if you want to talk there.

**Comment by 256colormode** [comment]
ok guess were gonna take it to dms
